#### general settings
name: 000_EDVR_LUMO_M_5f_REDS_pretrained
use_tb_logger: true
model: video_base
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: LUMO
    mode: LUMO 
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: ../datasets/LUMO/train_gt_wval.lmdb
    dataroot_LQ: ../datasets/LUMO/train_d4_wval.lmdb
    cache_keys: meta_info.pkl

    N_frames: 5
    use_shuffle: true 
    n_workers: 4 # per GPU
    batch_size: 16
    GT_size: 480 # 240
    LQ_size: 120 # 60
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: LUMO
    mode: video_test
    dataroot_GT: ../datasets/LUMO/val_gt
    dataroot_LQ: ../datasets/LUMO/val_d4
    cache_data: True
    N_frames: 5
    padding: new_info

#### network structures
network_G:
  which_model_G: EDVR
  nf: 64 # debug
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10 # debug
  predeblur: false
  HR_in: false
  w_TSA: true

#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/EDVR_M_x4_SR_REDS.pth
  strict_load: False
  resume_state: ~ #../experiments/000_EDVR_LUMO_M_5f_REDS_pretrained/training_state/160000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 300000 #x2
  ft_tsa_only: 25000 # x2
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
